src/trackyr/notification_agents/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired

class NotificationAgentForm(FlaskForm):
    MODULE_CHOICES = [(0,'Please Select a Module'), (1,'Discord')]
    module = SelectField('Module', validators=[DataRequired()], coerce=int, choices=MODULE_CHOICES)
    name = StringField('Name', validators=[DataRequired()])
    webhook_url = StringField('Webhook URL')
    username = StringField('Username')
    icon = StringField('Icon')
    channel = StringField('Channel')
    submit = SubmitField('Save')
    test = SubmitField('Test')

src/trackyr/sources/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired

class SourceForm(FlaskForm):
    MODULE_CHOICES = [(0,'Please Select a Module'), (1,'Kijiji')]
    module = SelectField('Module', validators=[DataRequired()], coerce=int, choices=MODULE_CHOICES)
    name = StringField('Name', validators=[DataRequired()])
    website = StringField('Website')
    location = StringField('Location')
    range = StringField('Range (km)')
    # subreddit = StringField('Subreddit (without "r/" , "r/localsales" --> "localsales")')
    submit = SubmitField('Save')
    test = SubmitField('Test')

src/trackyr/tasks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired

class TaskForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    frequency = StringField('Frequency (Minutes)', validators=[DataRequired()])
    source = SelectField('Source', validators=[DataRequired()], coerce=int)
    notification_agent = SelectField('Notification Agent', validators=[DataRequired()], coerce=int)
    colour_flag = StringField('Colour Flag')
    must_contain = StringField('Must Contain')
    exclude = StringField('Exclude')
    prime_count = StringField('Number of ads to show when the task is created')
    submit = SubmitField('Save')

src/trackyr/main/routes.py
from flask import render_template, request, Blueprint
from trackyr.models import NotificationAgent, Source, Task

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
@main.route("/dashboard")
def dashboard():
    return render_template('dashboard.html')

@main.route("/tasks")
def tasks():
    sources = Source.query.all()
    notification_agents = NotificationAgent.query.all()
    tasks = Task.query.all()
    return render_template('tasks.html', title='Tasks', sources=sources, notification_agents=notification_agents, tasks=tasks)

@main.route("/notification_agents")
def notification_agents():
    notification_agents = NotificationAgent.query.all()
    return render_template('notification-agents.html', title='Notification Agents', notification_agents=notification_agents)

@main.route("/sources")
def sources():
    sources = Source.query.all()
    return render_template('sources.html', title='Sources', sources=sources)

@main.route("/trackyr_config")
def trackyr_config():
    return render_template('trackyr-config.html', title='Config')

src/trackyr/notification_agents/routes.py
from flask import (Blueprint, abort, flash, redirect, render_template, request, url_for)
from trackyr import db
from trackyr.models import NotificationAgent
from trackyr.notification_agents.forms import NotificationAgentForm

import json
import requests

import lib.core.notif_agent as notifAgent

notification_agents = Blueprint('notification_agents', __name__)

@notification_agents.route("/notification_agents/create", methods=['GET', 'POST'])
def create_notification_agents():
    form = NotificationAgentForm()
    if form.validate_on_submit():
        if form.test.data:
            # This button will send a test notification to the Notification Agent.
            # Will need to add IF statements to send different notification messages to different agents.

            webhook_url=form.webhook_url.data
            if form.username.data:
                username=form.username.data
            else:
                username="Trackyr"

            Dict = {1: 'discord'}

            test_notify = notifAgent.NotifAgent(module=Dict.get(form.module.data), module_properties={'webhook':webhook_url,'botname':username})
            notifAgent.test_notif_agent(test_notify)
            
            # Notification message on webui
            flash("A test message has been sent to your notification agent", "notification")
        else:
            notification_agent = NotificationAgent(module=form.module.data,
                                                    name=form.name.data,
                                                    webhook_url=form.webhook_url.data,
                                                    username=form.username.data,
                                                    icon=form.icon.data,
                                                    channel=form.channel.data)
            db.session.add(notification_agent)
            db.session.commit()
            flash('Your notification agent has been saved!', 'top_flash_success')
            return redirect(url_for('main.notification_agents'))
    return render_template('create-notification-agent.html', title='Create Notification Agent', 
                            form=form, legend='Create Notification Agent')

@notification_agents.route("/notification_agents/<int:notification_agent_id>/edit", methods=['GET', 'POST'])
def edit_notification_agent(notification_agent_id):
    notification_agents = NotificationAgent.query.get_or_404(notification_agent_id)
    form = NotificationAgentForm()
    if form.validate_on_submit():
        notification_agents.id = notification_agent_id
        notification_agents.module = form.module.data
        notification_agents.name = form.name.data
        notification_agents.webhook_url = form.webhook_url.data
        notification_agents.username = form.username.data
        notification_agents.icon = form.icon.data
        notification_agents.channel = form.channel.data
        db.session.commit()
        flash('Your notification agent has been updated!', 'top_flash_success')
        return redirect(url_for('main.notification_agents', notification_agent_id=notification_agents.id))
    elif request.method == 'GET':
        form.module.data = notification_agents.module
        form.name.data = notification_agents.name
        form.webhook_url.data = notification_agents.webhook_url
        form.username.data = notification_agents.username
        form.icon.data = notification_agents.icon
        form.channel.data = notification_agents.channel
    return render_template('create-notification-agent.html', title='Update Notification Agent', 
                            form=form, legend='Update Notification Agent')

@notification_agents.route("/notification_agents/<int:notification_agent_id>/delete", methods=['GET', 'POST'])
def delete_notification_agent(notification_agent_id):
    notification_agent = NotificationAgent.query.get_or_404(notification_agent_id)
    db.session.delete(notification_agent)
    db.session.commit()
    flash('Your notification agent has been deleted.', 'top_flash_success')
    return redirect(url_for('main.notification_agents'))

src/trackyr/sources/routes.py
from flask import (Blueprint, abort, flash, redirect, render_template, request, url_for)

from trackyr import db
from trackyr.models import Source
from trackyr.sources.forms import SourceForm

import lib.core.source as prime

sources = Blueprint('sources', __name__)

@sources.route("/sources/create", methods=['GET', 'POST'])
def create_source():
    form = SourceForm()
    if form.validate_on_submit():
        if form.test.data:
            web_url=form.website.data

            Dict = {1: 'kijiji'}

            prime_source = prime.Source(module=Dict.get(form.module.data), module_properties={'url':web_url,'botname':"prime"})

            try:
                total_ads = prime.test_webui_source(prime_source).total_new_ads
            except:
                message = "Not a valid source"
            else:
                message = f"Found {total_ads} new ads" \
                    if total_ads != 1 else "Found 1 new ad"
            finally:
                if web_url == "":
                    message = "Not a valid source"
                flash(message, "notification")

        else:
            source = Source(module=form.module.data,
                            name=form.name.data,
                            website=form.website.data,
                            location=form.location.data,
                            range=form.range.data,
                            # subreddit=form.subreddit.data
                            )
            db.session.add(source)
            db.session.commit()
            flash('Your source has been saved!', 'top_flash_success')
            return redirect(url_for('main.sources'))
    return render_template('create-source.html', title='Create Source', 
                            form=form, legend='Create Source')

@sources.route("/sources/<int:source_id>/edit", methods=['GET', 'POST'])
def edit_source(source_id):
    source = Source.query.get_or_404(source_id)
    form = SourceForm()
    if form.validate_on_submit():
        if form.test.data:
            web_url=form.website.data

            Dict = {1: 'kijiji'}

            prime_source = prime.Source(module=Dict.get(form.module.data), module_properties={'url':web_url,'botname':"prime"})

            try:
                total_ads = prime.test_webui_source(prime_source).total_new_ads
            except:
                message = "Not a valid source"
            else:
                message = f"Found {total_ads} new ads" \
                    if total_ads != 1 else "Found 1 new ad"
            finally:
                if web_url == "":
                    message = "Not a valid source"
                flash(message, "notification")

        else:
            source.module = form.module.data
            source.name = form.name.data
            source.website = form.website.data
            source.location = form.location.data
            source.range = form.range.data
            # source.subreddit = form.subreddit.data
            db.session.commit()
            flash('Your source has been updated!', 'top_flash_success')
            return redirect(url_for('main.sources', source_id=source.id))
    elif request.method == 'GET':
        form.module.data = source.module
        form.name.data = source.name
        form.website.data = source.website
        form.location.data = source.location
        form.range.data = source.range
        # form.subreddit.data = source.subreddit
    return render_template('create-source.html', title='Update Source', 
                            form=form, legend='Update Source')

@sources.route("/sources/<int:source_id>/delete", methods=['GET', 'POST'])
def delete_source(source_id):
    source = Source.query.get_or_404(source_id)
    db.session.delete(source)
    db.session.commit()
    flash('Your source has been deleted.', 'top_flash_success')
    return redirect(url_for('main.sources'))

src/trackyr/tasks/routes.py
from flask import (Blueprint, abort, flash, redirect, render_template, request, url_for)

from trackyr import db
from trackyr.models import Task, Source, NotificationAgent
from trackyr.tasks.forms import TaskForm

from lib.utils import cron
import lib.core.task as prime

tasks = Blueprint('tasks', __name__)

@tasks.route("/tasks/create", methods=['GET', 'POST'])
def create_tasks():
    form = TaskForm()
    
    form.source.choices=get_source_choices()
    form.notification_agent.choices=get_notification_agents_choices()
    
    if form.validate_on_submit():
        task = Task(name=form.name.data, 
                    frequency=form.frequency.data, 
                    source=form.source.data,
                    notification_agent=form.notification_agent.data,
                    colour_flag=form.colour_flag.data, 
                    must_contain=form.must_contain.data, 
                    exclude=form.exclude.data)
        db.session.add(task)
        db.session.commit()

        cron.add(int(form.frequency.data), "minutes")
        
        ## Need to get the task that was just created to send for priming.
        prime_task = prime.Task(source_ids=[form.source.data], notif_agent_ids=[form.notification_agent.data], include=[form.must_contain.data], exclude=[form.exclude.data])
        prime.prime(prime_task, notify=True, recent_ads=int(form.prime_count.data))

        flash('Your task has been created!', 'top_flash_success')
        return redirect(url_for('main.tasks'))
    return render_template('create-task.html', title='Create a Task', 
                            form=form, legend='Create a Task')
    
@tasks.route("/tasks/<int:task_id>/edit", methods=['GET', 'POST'])
def edit_task(task_id):
    task = Task.query.get_or_404(task_id)
    form = TaskForm()

    form.source.choices=get_source_choices()
    form.notification_agent.choices=get_notification_agents_choices()

    if form.validate_on_submit():
        task.id = task_id
        task.name = form.name.data
        task.frequency = form.frequency.data
        task.source = form.source.data
        task.notification_agent = form.notification_agent.data
        task.colour_flag = form.colour_flag.data
        task.must_contain = form.must_contain.data
        task.exclude = form.exclude.data
        db.session.commit()
        flash('Your task has been updated!', 'top_flash_success')
        return redirect(url_for('main.tasks', task_id=task.id))
    elif request.method == 'GET':
        form.name.data = task.name
        form.frequency.data = task.frequency
        form.source.data = task.source
        form.notification_agent.data = task.notification_agent
        form.colour_flag.data = task.colour_flag
        form.must_contain.data = task.must_contain
        form.exclude.data = task.exclude
    return render_template('create-task.html', title='Update Task', 
                            form=form, legend='Update Task')

@tasks.route("/tasks/<int:task_id>/delete", methods=['GET', 'POST'])
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()
    flash('Your task has been deleted.', 'top_flash_success')
    return redirect(url_for('main.tasks'))

def get_source_choices():
    source_choices = db.session.query(Source.name).all()
    return [(g.id, g.name) for g in Source.query.order_by('name')]
    
def get_notification_agents_choices():
    notification_agents_choices = db.session.query(NotificationAgent.name).all()
    return [(g.id, g.name) for g in NotificationAgent.query.order_by('name')]

src/trackyr/templates/dashboard.html
{% extends "layout.html" %}
{% block content %}
    <h1>Dashboard</h1>
    <p>This is will be the main page where we can see cool graphs and data and stuff.</p>
{% endblock content %}

src/trackyr/templates/layout.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

        {% if title %}
            <title>Trackyr - {{ title }}</title>
        {% else %}
            <title>Trackyr</title>
        {% endif %}

    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">Trackyr</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{{ url_for('main.dashboard') }}">Dashboard</a>
                        </div>
                        <!-- Navbar Right Side-->
                        <div class="navbar-nav">
                            <a class="nav-item nav-link" href="{{ url_for('main.sources') }}">Sources</a>
                            <a class="nav-item nav-link" href="{{ url_for('main.notification_agents') }}">Notification Agents</a>
                            <a class="nav-item nav-link" href="{{ url_for('main.tasks') }}">Tasks</a>
                            <a class="nav-item nav-link" href="{{ url_for('main.trackyr_config') }}">Config</a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-12">
                    {% with messages = get_flashed_messages(category_filter=["top_flash_success"]) %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
            </div>
        </main>
        <div class="row">
            <div class="container col-md-9">
            </div>

            <div class="container col-md-3" id="notificationMessage">
                {% with notifications = get_flashed_messages(category_filter=["notification"]) %}
                    {% if notifications %}
                        {%- for message in notifications %}
                            <div class="alert alert-info alert-dismissible fade show" role="alert">
                                <span>{{ message }}</span>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor -%}
                    {% endif %}
                {% endwith %}
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script type="text/javascript">window.setTimeout("document.getElementById('notificationMessage').style.display='none';", 5000); </script>
        <script>
            $("#sourceSelection").change(function() {
                if ($(this).val() == 1) {
                    $('#kijijiDiv').show();
                //     $('#redditDiv').hide();
                // } else if ($(this).val() == 2) {
                //     $('#redditDiv').show();
                //     $('#kijijiDiv').hide();
                } else {
                    $('#kijijiDiv').hide();
                    // $('#redditDiv').hide();
                }
            });
            $("#sourceSelection").trigger("change");

            $("#notificationAgentSelection").change(function() {
                if ($(this).val() == 1) {
                    $('#discordDiv').show();
                //     $('#slackDiv').hide();
                // } else if ($(this).val() == 2) {
                //     $('#slackDiv').show();
                //     $('#discordDiv').hide();
                } else {
                    $('#discordDiv').hide();
                    // $('#slackDiv').hide();
                }
            });
            $("#notificationAgentSelection").trigger("change");
        </script>
    </body>
</html>

src/trackyr/templates/notification-agents.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    <p>
        <a class="btn btn-primary" href="{{ url_for('notification_agents.create_notification_agents') }}">Create Notification Agents</a>
    </p>

    <h3>Discord</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Webhook URL</th>
                <th scope="col">Username</th>
                <th scope="col">Icon</th>
                <th scope="col">Channel</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for agent in notification_agents %}
                {% if agent.module == 1 %} 
                    <tr>
                        <td>{{ agent.name }}</td>
                        <td>{{ agent.webhook_url }}</td>
                        <td>{{ agent.username }}</td>
                        <td>{{ agent.icon }}</td>
                        <td>{{ agent.channel }}</td>
                        <td><a class="btn btn-secondary btm-sm mt-1 mb-1" href="{{ url_for('notification_agents.edit_notification_agent', notification_agent_id=agent.id) }}">Edit</a></td>
                        <td><a class="btn btn-danger btm-sm mt-1 mb-1" href="{{ url_for('notification_agents.delete_notification_agent', notification_agent_id=agent.id) }}">Delete</a></td>
                    </tr>  
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    <!-- <h3>Slack</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for agent in notification_agents %}
                {% if agent.module == 2 %}
                    <tr>
                        <td>{{ source.name }}</td>
                        <td><a class="btn btn-secondary btm-sm mt-1 mb-1" href="{{ url_for('notification_agents.edit_notification_agent', notification_agent_id=agent.id) }}">Edit</a></td>
                        <td><a class="btn btn-danger btm-sm mt-1 mb-1" href="{{ url_for('notification_agents.delete_notification_agent', notification_agent_id=agent.id) }}">Delete</a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table> -->

    <p>
        <a class="btn btn-primary" href="{{ url_for('notification_agents.create_notification_agents') }}">Create Notification Agents</a>
    </p>
{% endblock content %}

src/trackyr/templates/sources.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    <p>
        <a class="btn btn-primary" href="{{ url_for('sources.create_source') }}">Create Sources</a>
    </p>

    <h3>Kijiji</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Website</th>
                <th scope="col">Location</th>
                <th scope="col">Range</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for source in sources %}
                {% if source.module == 1 %} 
                    <tr>
                        <td>{{ source.name }}</td>
                        <td>{{ source.website }}</td>
                        <td>{{ source.location }}</td>
                        <td>{{ source.range }} km</td>
                        <td><a class="btn btn-secondary btm-sm mt-1 mb-1" href="{{ url_for('sources.edit_source', source_id=source.id) }}">Edit</a></td>
                        <td><a class="btn btn-danger btm-sm mt-1 mb-1" href="{{ url_for('sources.delete_source', source_id=source.id) }}">Delete</a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    <!-- <h3>Reddit</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Subreddit</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for source in sources %}
                {% if source.module == 2 %}
                    <tr>
                        <td>{{ source.name }}</td>
                        <td>{{ source.subreddit }}</td>
                        <td><a class="btn btn-secondary btm-sm mt-1 mb-1" href="{{ url_for('sources.edit_source', source_id=source.id) }}">Edit</a></td>
                        <td><a class="btn btn-danger btm-sm mt-1 mb-1" href="{{ url_for('sources.delete_source', source_id=source.id) }}">Delete</a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table> -->

    <p>
        <a class="btn btn-primary" href="{{ url_for('sources.create_source') }}">Create Sources</a>
    </p>
{% endblock content %}

src/trackyr/templates/tasks.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    <p>
        <a class="btn btn-primary" href="{{ url_for('tasks.create_tasks') }}">Create Tasks</a>
    </p>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Frequency</th>
                <th scope="col">Source</th>
                <th scope="col">Notification Agent</th>
                <th scope="col">Must Contain</th>
                <th scope="col">Exclude(s)</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
                <tr>
                    <td>{{ task.name }}</td>
                    <td>{{ task.frequency }} Minutes</td>
                    {% for source in sources %}
                        {% if task.source == source.id %}
                            <td>{{ source.name }}</td>
                        {% endif %}
                    {% endfor %}
                    {% for notification_agent in notification_agents %}
                        {% if task.notification_agent == notification_agent.id %}
                            <td>{{ notification_agent.name }}</td>
                        {% endif %}
                    {% endfor %}
                    <td>{{ task.must_contain }}</td>
                    <td>{{ task.exclude }}</td>
                    <td><a class="btn btn-secondary btm-sm mt-1 mb-1" href="{{ url_for('tasks.edit_task', task_id=task.id) }}">Edit</a></td>
                    <td><a class="btn btn-danger btm-sm mt-1 mb-1" href="{{ url_for('tasks.delete_task', task_id=task.id) }}">Delete</a></td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>

    <p>
        <a class="btn btn-primary" href="{{ url_for('tasks.create_tasks') }}">Create Tasks</a>
    </p>
{% endblock content %}

src/trackyr/templates/trackyr-config.html
{% extends "layout.html" %}
{% block content %}
    <h1>Trackyr Config</h1>
    <p>This is where we will set global variables.</p>
{% endblock content %}